name: sju_machine_learning
channels:
  - defaults
dependencies:
  - _tflow_select=2.2.0
  - abseil-cpp=20211102.0
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - appdirs=1.4.4
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=22.1.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - blinker=1.4
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bs4=4.12.2
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.01.10
  - cachetools=4.2.2
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cycler=0.11.0
  - flatbuffers=2.0.0
  - flit-core=3.8.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - gast=0.4.0
  - giflib=5.2.1
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - grpc-cpp=1.46.1
  - grpcio=1.42.0
  - h5py=3.7.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.4
  - intel-openmp=2021.4.0
  - joblib=1.1.1
  - jpeg=9e
  - keras=2.10.0
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=7.88.1
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libnghttp2=1.46.0
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libssh2=1.10.0
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - munkres=1.1.4
  - ncurses=6.4
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - oauthlib=3.2.2
  - openssl=1.1.1t
  - opt_einsum=3.3.0
  - packaging=23.0
  - pandas=1.5.3
  - pillow=9.4.0
  - pip=23.0.1
  - pooch=1.4.0
  - protobuf=3.20.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyjwt=2.4.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - python-flatbuffers=2.0
  - pytz=2022.7
  - re2=2022.04.01
  - readline=8.2
  - requests=2.28.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-learn=1.2.1
  - scipy=1.10.0
  - seaborn=0.12.2
  - setuptools=65.6.3
  - six=1.16.0
  - snappy=1.1.9
  - soupsieve=2.4
  - sqlite=3.40.1
  - tensorboard=2.10.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.10.0
  - tensorflow-base=2.10.0
  - tensorflow-estimator=2.10.0
  - termcolor=2.1.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tornado=6.2
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.14
  - werkzeug=2.2.3
  - wheel=0.35.1
  - wrapt=1.14.1
  - xz=5.2.10
  - yarl=1.8.1
  - zlib=1.2.13
  - zstd=1.5.4
  - pip:
    - mlxtend==0.22.0
prefix: /opt/anaconda3/envs/sju_machine_learning
